import "./globals.css";
import { Rajdhani } from "next/font/google";

const rajDhani = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-rajdhani",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rajDhani.variable}`}>{children}</body>
    </html>
  );
}
